version: "3.8"

services:
  gbans:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./gbans_test.yaml:/app/gbans.yaml
      - dl_cache:/app/.cache
    depends_on:
      - postgres
    networks:
      - test_network
    environment:
      database.dsn: postgres://gbans:gbans@postgres:5432/gbans
    command: make test

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: gbans
      POSTGRES_DB: gbans
      POSTGRES_PASSWORD: gbans
    networks:
      - test_network
    volumes:
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  dl_cache:

networks:
  test_network: