name: Docker Image CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GBANS_GENERAL_STEAM_KEY: ${{ secrets.GBANS_GENERAL_STEAM_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: hmmm
        run: ls -la
      - name: Build the docker-compose stack
        run: docker-compose up --exit-code-from gbans-test
